name: Lint build test

on:
  push:
  pull_request_target:
    branches:
      - 'master'

jobs:
  lint:
    needs: []
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - name: Run lint
        run: |
          yarn install
          yarn run lint
  
  build:
    needs: [lint]
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - name: Build bundles
        run: |
          yarn install
          yarn run rollup
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}-${{ github.run_id }}-bundles
          path: dist
          retention-days: 3

  test:
    needs: [build]
    runs-on: ubuntu-20.04
    env:
      MOCHA_FILE: test-results/mocha/test-results.xml
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}-${{ github.run_id }}-bundles
      - name: Run tests
        run: |
          yarn install
          yarn run test-output
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}-${{ github.run_id }}-${{ github.job }}-test-results
          path: test-results
          retention-days: 3
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1.27
        with:
          files: test-results/**/*.xml
  
  release:
    needs: [test]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}-${{ github.run_id }}-bundles
      - name: Release, publish package
        run: |
          yarn install
